http://cs231n.github.io/python-numpy-tutorial/

In [ ]:
# quicksort
# enumurate (index while looping)
# list comprehension
# set comprehension
# tuple
# class --
# np array indexing

In [17]:
def quicksort(arr):
    if len(arr) <=1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

quicksort([3,6,8,10,1,2,1])

[1, 1, 2, 3, 6, 8, 10]

In [43]:
# set
from math import sqrt
setnum = {int(sqrt(x)) for x in range(30)}
listnum = [int(sqrt(x)) for x in range(30)]
# listnum all root value from 0 to 29
setnum # no duplicate values

{0, 1, 2, 3, 4, 5}

In [48]:
# tuple
d = {(x, x + 1): x for x in range(10)}
t = (5, 6)
print(d)
d[t]

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}


5

In [49]:
import numpy as np

In [52]:
a = np.array([1,2,3])              # Create a rank 1 array
print(a.shape)
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape) 

(3,)
(2, 3)


In [54]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [59]:
a[1,:]

array([5, 6, 7, 8])

In [63]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
               [[100,101,102],
                [110,112,113]]])

c.shape

(2, 2, 3)

In [75]:
c[1:,:,2]

array([[102, 113]])